version: '3.1'

services:
  products_api:
    container_name: produto-api
    image: arturbertoni/produto-api:v1
    build: ./produto-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - URL_POSTGRES=jdbc:postgresql://postgres:5432/produto-api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12022004
      - SPRING_PROFILES_ACTIVE=dev
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=12022004
      - RABBITMQ_DEFAULT_HOST=rabbitmq
    depends_on:
      - postgres
      - rabbitmq

  producer:
    container_name: producer
    image: arturbertoni/producer:v1
    build: ./producer
    restart: always
    ports:
      - "8081:8080"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=12022004
      - RABBITMQ_DEFAULT_HOST=rabbitmq
      - PRODUTO_API_URL=produto-api
      - PRODUTO_API_PORT=8080
    depends_on:
      - products_api
      - rabbitmq

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=produto-api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12022004

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmqData:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=12022004