CREATE TABLE IF NOT EXISTS tb_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    bar_code BIGINT,
    category VARCHAR(255),
    code VARCHAR(255),
    color VARCHAR(255),
    description VARCHAR(255),
    expiration_date TIMESTAMP,
    gross_amount DECIMAL(19,2),
    manufacturing_date TIMESTAMP,
    material VARCHAR(255),
    name VARCHAR(255),
    price DECIMAL(19,2),
    quantity INTEGER,
    series VARCHAR(255),
    taxes decimal(19,2),
    PRIMARY KEY (id)
)